import { ArrowUpRight, HeartHandshake, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import { Link } from "wouter";
import { PageIntro, PublicLayout, usePageMeta } from "@/components/PublicLayout";
import { trpc } from "@/lib/trpc";

const values = [["Unity", "Friendship, solidarity and meaningful relationships."], ["Empowerment", "Skills, confidence, knowledge and opportunity."], ["Service", "Compassion, friendship, teamwork and responsible leadership."], ["Inclusivity", "Equality, dignity, diversity and meaningful participation for all."], ["Resilience", "Practical support for people and communities to thrive."], ["Innovation", "Creativity, learning, research and practical solutions."], ["Integrity", "Honesty, transparency, accountability and professionalism."], ["Our focus areas", "Lifelong friendships and social support; economic empowerment and financial literacy; community service; entrepreneurship and innovation; skills development; wellness; diversity and creative arts."]];
const focusAreas = ["Lifelong friendships & social support", "Economic empowerment & financial literacy", "Community service & charity initiatives", "Entrepreneurship & innovation", "Skills development & leadership training", "Adventure, wellness & recreation", "Diversity, inclusion & creative arts"];
export default function About() {
  usePageMeta("About EFEN", "Learn about EFEN's mission, vision, values and friendship-led approach to inclusive community development.");
  const settings = trpc.site.settings.useQuery();
  const about = settings.data?.about;
  return <PublicLayout><main><PageIntro eyebrow="About EFEN" title={<>A network built around <em>possibility.</em></>} copy={about?.intro ?? "Eminent Friends Empowerment Network is a non-profit, non-political, non-sectarian and community-focused organization based in Soroti City, Eastern Uganda."} /><section className="content-section"><div className="container two-column-copy"><div><h2>{about?.purposeTitle ?? "Building bridges between people and opportunity."}</h2></div><div><p className="lead-copy">{about?.purposeLead ?? "We believe stronger relationships can open practical pathways to livelihoods, leadership, participation and lasting change."}</p><p>{about?.purposeBody ?? "EFEN brings together communities, young people, professionals, mentors, institutions, businesses, development partners and other stakeholders to create a more inclusive, resilient and prosperous future."}</p></div></div></section><section className="mission-band"><div className="container mission-grid"><div><span>Our vision</span><h2>{about?.vision ?? "A world with stronger social connections and networks that empower people and communities to prosper."}</h2></div><div><span>Our mission</span><p>{about?.mission ?? "To empower individuals and communities through friendship and stronger social connections, advancing inclusive development, sustainable livelihoods, ethical leadership, innovation and partnerships for lasting prosperity."}</p><Link className="button button-light" href="/work">Explore our work <ArrowUpRight size={16} /></Link></div></div></section><section className="values-section"><div className="container"><div className="section-heading-simple"><h2>{about?.valuesTitle ?? "Values are the way the work feels."}</h2></div><div className="values-grid">{values.map(([title, copy], index) => <article key={title}><b>0{index + 1}</b><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section><section className="beliefs-section"><div className="container beliefs-layout"><div><h2>{about?.beliefsTitle ?? "Connect. Empower. Act. Transform."}</h2></div><div className="beliefs-list"><p><UsersRound size={17} /><span><strong>Connect</strong> People need meaningful relationships and networks.</span></p><p><Sparkles size={17} /><span><strong>Empower</strong> People need skills, knowledge, confidence and opportunities.</span></p><p><HeartHandshake size={17} /><span><strong>Act</strong> Communities become stronger when people act together.</span></p><p><ShieldCheck size={17} /><span><strong>Transform</strong> Sustainable action creates lasting positive change.</span></p></div></div></section><section className="page-next"><div className="container page-next-inner"><span /> <Link href="/work">See how EFEN works <ArrowUpRight size={17} /></Link></div></section></main></PublicLayout>;
}
