import { ArrowUpRight, HeartHandshake, Lightbulb, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import { Link } from "wouter";
import { PageIntro, PublicLayout, usePageMeta } from "@/components/PublicLayout";

const values = [["Integrity", "Honesty, transparency, accountability and professionalism."], ["Inclusion", "Equality, dignity, diversity and meaningful participation for all."], ["Innovation", "Creativity, learning, research and practical solutions."], ["Service", "Compassion, friendship, teamwork and responsible leadership."]];

export default function About() {
  usePageMeta("About EFEN", "Learn about EFEN's mission, vision, values and friendship-led approach to inclusive community development.");
  return <PublicLayout><main><PageIntro eyebrow="About EFEN" title={<>A network built around <em>possibility.</em></>} copy="Eminent Friends Empowerment Network is a non-profit, non-political, non-sectarian and community-focused organization based in Soroti City, Eastern Uganda." /><section className="content-section"><div className="container two-column-copy"><div><span className="eyebrow"><i className="eyebrow-line" /> Our purpose</span><h2>Building bridges between people and opportunity.</h2></div><div><p className="lead-copy">We believe stronger relationships can open practical pathways to livelihoods, leadership, participation and lasting change.</p><p>EFEN brings together communities, young people, professionals, mentors, institutions, businesses, development partners and other stakeholders to create a more inclusive, resilient and prosperous future.</p></div></div></section><section className="mission-band"><div className="container mission-grid"><div><span>Our vision</span><h2>A world with stronger social connections and networks that empower people and communities to prosper.</h2></div><div><span>Our mission</span><p>To empower individuals and communities through friendship and stronger social connections, advancing inclusive development, sustainable livelihoods, ethical leadership, innovation and partnerships for lasting prosperity.</p><Link className="button button-light" href="/work">Explore our work <ArrowUpRight size={16} /></Link></div></div></section><section className="values-section"><div className="container"><div className="section-heading-simple"><span className="eyebrow"><i className="eyebrow-line" /> What guides us</span><h2>Values are the way the work feels.</h2></div><div className="values-grid">{values.map(([title, copy], index) => <article key={title}><b>0{index + 1}</b><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section><section className="beliefs-section"><div className="container beliefs-layout"><div><span className="eyebrow light"><i className="eyebrow-line" /> What we believe</span><h2>Connect. Empower. Act. Transform.</h2></div><div className="beliefs-list"><p><UsersRound size={17} /><span><strong>Connect</strong> People need meaningful relationships and networks.</span></p><p><Sparkles size={17} /><span><strong>Empower</strong> People need skills, knowledge, confidence and opportunities.</span></p><p><HeartHandshake size={17} /><span><strong>Act</strong> Communities become stronger when people act together.</span></p><p><ShieldCheck size={17} /><span><strong>Transform</strong> Sustainable action creates lasting positive change.</span></p></div></div></section><section className="page-next"><div className="container page-next-inner"><span>Next page</span><Link href="/work">See how EFEN works <ArrowUpRight size={17} /></Link></div></section></main></PublicLayout>;
}
