import { useState } from "react";
import { ArrowUpRight, ChevronDown } from "lucide-react";
import { Link } from "wouter";
import { PageIntro, PublicLayout, usePageMeta } from "@/components/PublicLayout";

const faqs = [["What is EFEN?", "Eminent Friends Empowerment Network is a non-profit, non-political, non-sectarian and community-focused organization based in Soroti City, Eastern Uganda."], ["Who does EFEN work with?", "EFEN works alongside young people, women and girls, children, persons with disabilities, marginalized communities, professionals, mentors, institutions, businesses and development partners."], ["What is Connect4Change?", "Connect4Change is EFEN's youth-focused innovation model. It helps young people turn social connections into practical pathways to opportunities, mentorship, livelihoods, leadership and community action."], ["How can I get involved?", "You can become a member, volunteer, partner with EFEN, support the work or share an opportunity. Visit the Get involved page to explore the closest starting point."], ["Where does EFEN work?", "EFEN's head office is in Soroti City, Eastern Uganda. Its work is community-focused and partnerships can extend the reach of the network where there is a clear shared purpose."], ["How does EFEN approach safeguarding?", "EFEN is committed to child protection, protection from sexual exploitation, abuse and harassment, non-discrimination, safe participation, confidential reporting, responsible conduct and data protection."], ["Are official contact details available?", "The source organization brief still has placeholder email, telephone and safeguarding contacts. Those should be added by EFEN before public launch rather than invented in the website."]];

export default function Faqs() {
  const [open, setOpen] = useState(0);
  usePageMeta("FAQs", "Frequently asked questions about EFEN, Connect4Change, participation, safeguarding and the communities the network serves.");
  return <PublicLayout><main><PageIntro eyebrow="FAQs" title={<>Good questions make <em>better connections.</em></>} copy="A short, practical guide to EFEN, its focus, participation pathways and the information still to be confirmed." /><section className="faq-section"><div className="container faq-layout"><div><span className="eyebrow"><i className="eyebrow-line" /> Before you connect</span><h2>Start with what you need to know.</h2><p>We are keeping this page specific and honest. Official contact and safeguarding details can be added from the admin workspace when confirmed.</p><Link className="text-button" href="/involved">Find a participation path <ArrowUpRight size={16} /></Link></div><div className="faq-list">{faqs.map(([question, answer], index) => <div className={`faq-item ${open === index ? "open" : ""}`} key={question}><button onClick={() => setOpen(open === index ? -1 : index)}><span>{question}</span><ChevronDown size={18} /></button>{open === index && <p>{answer}</p>}</div>)}</div></div></section></main></PublicLayout>;
}
