import { ArrowLeft, ShieldCheck } from "lucide-react";
import { Link, useRoute } from "wouter";
import { PageIntro, PublicLayout, usePageMeta } from "@/components/PublicLayout";
import { trpc } from "@/lib/trpc";

export default function InfoPage() {
  const [safeguarding] = useRoute("/safeguarding");
  const title = safeguarding ? "Safeguarding" : "Privacy";
  const settings = trpc.site.settings.useQuery();
  const contact = settings.data?.contact;
  usePageMeta(title, safeguarding ? "EFEN safeguarding commitments for safe, respectful and accessible participation." : "EFEN privacy information and responsible data handling principles.");
  return <PublicLayout><main><PageIntro eyebrow={title} title={safeguarding ? <>People first. <em>Safety always.</em></> : <>Trust is part of the <em>connection.</em></>} copy={safeguarding ? "EFEN is committed to child protection, safe participation, dignity, non-discrimination and responsible conduct." : "EFEN is committed to responsible information handling, clear purpose and respect for the people who connect with the network."} /><section className="info-page-section"><div className="container info-page-copy"><div className="info-page-icon"><ShieldCheck size={22} /></div><span className="eyebrow"><i className="eyebrow-line" /> Information to confirm before launch</span><h2>{safeguarding ? "The right standards should be visible in every interaction." : "Good data practice keeps people in control."}</h2>{safeguarding ? <><p>EFEN's commitments include child protection, protection from sexual exploitation, abuse and harassment, non-discrimination, safe participation, confidential reporting, responsible conduct and data protection.</p><p>{contact?.safeguardingEmail || contact?.safeguardingPhone ? <>Official reporting channels: {contact.safeguardingEmail && <a href={`mailto:${contact.safeguardingEmail}`}>{contact.safeguardingEmail}</a>}{contact.safeguardingEmail && contact.safeguardingPhone ? " · " : ""}{contact.safeguardingPhone && <a href={`tel:${contact.safeguardingPhone}`}>{contact.safeguardingPhone}</a>}.</> : "The authorized administrator should add official safeguarding reporting channels before public launch."}</p></> : <><p>EFEN should publish the final privacy notice, lawful basis, retention period, data subject rights and official contact before collecting personal information through a production form.</p><p>{contact?.email ? <>For privacy questions, contact <a href={`mailto:${contact.email}`}>{contact.email}</a>.</> : "Official privacy contact details can be added from the private content studio."}</p></>}<Link className="text-button" href="/faqs"><ArrowLeft size={16} /> Back to FAQs</Link></div></section></main></PublicLayout>;
}
