import { ArrowUpRight, Handshake, Send, Sparkles, UsersRound } from "lucide-react";
import { Link } from "wouter";
import { PageIntro, PublicLayout, usePageMeta } from "@/components/PublicLayout";
import { toast } from "sonner";

const paths = [[UsersRound, "Become a member", "Bring your perspective, lived experience and network into a community of people building what is possible."], [Sparkles, "Volunteer", "Share your time, skills, local knowledge or practical support with a project that needs another pair of hands."], [Handshake, "Become a partner", "Build a thoughtful pathway with EFEN, communities and the people closest to the opportunity."], [Send, "Share an opportunity", "Open a door through a job, mentor, training, market link, resource or connection." ]];

export default function Involved() {
  usePageMeta("Get involved", "Find a way to participate in EFEN's community-powered work as a member, volunteer, partner or opportunity holder.");
  return <PublicLayout><main><PageIntro eyebrow="Get involved" title={<>There is a place for your <em>yes.</em></>} copy="Whether you bring time, expertise, resources or an opportunity, your next connection can help someone move forward." /><section className="involved-page-section"><div className="container involved-page-grid">{paths.map(([Icon, title, copy], index) => <article className="involved-page-card" key={title as string}><div className="involved-card-number">0{index + 1}</div><Icon size={24} /><h2>{title as string}</h2><p>{copy as string}</p><button className="text-button" onClick={() => toast(`${title} is ready for official EFEN contact details to be added.`)}>Choose this pathway <ArrowUpRight size={16} /></button></article>)}</div></section><section className="partner-band"><div className="container partner-band-grid"><div><span className="eyebrow light"><i className="eyebrow-line" /> A useful next step</span><h2>Bring an opportunity into the network.</h2></div><div><p>EFEN is creating practical pathways between communities, mentors, institutions, businesses and development partners. Share what you can offer and who it could help.</p><Link className="button button-light" href="/faqs">Read common questions <ArrowUpRight size={16} /></Link></div></div></section><section className="safeguarding-callout"><div className="container"><span className="eyebrow"><i className="eyebrow-line" /> People first. Safety always.</span><h2>Participation should feel safe, respectful and accessible.</h2><Link className="text-button" href="/safeguarding">Read EFEN safeguarding commitments <ArrowUpRight size={16} /></Link></div></section></main></PublicLayout>;
}
