import { ArrowLeft, ArrowUpRight, FolderOpen, Loader2 } from "lucide-react";
import { Link, useRoute } from "wouter";
import { PageIntro, PublicLayout, usePageMeta } from "@/components/PublicLayout";
import { trpc } from "@/lib/trpc";
import projectOneImage from "@/assets/efen-comm1.jpeg";
import projectTwoImage from "@/assets/efen-comm3.jpeg";
import projectThreeImage from "@/assets/efen-comm2.jpeg";
const parseImages = (value: string | null | undefined) => { try { const parsed = value ? JSON.parse(value) : []; return Array.isArray(parsed) ? parsed.filter((item): item is string => typeof item === "string").slice(0, 5) : []; } catch { return []; } };
const parseMeta = (value: string | null | undefined) => { try { const parsed = value ? JSON.parse(value) : []; return Array.isArray(parsed) ? parsed.filter((item) => item && typeof item.url === "string").slice(0, 5) as Array<{ url: string; caption?: string; alt?: string }> : []; } catch { return []; } };
export default function ProjectDetail() {
  const [, params] = useRoute<{ slug: string }>("/work/:slug"); const project = trpc.projects.bySlug.useQuery({ slug: params?.slug ?? "" }, { enabled: Boolean(params?.slug) }); usePageMeta(project.data?.title ?? "Project", project.data?.summary ?? "A project from EFEN's community-powered work.");
  if (project.isLoading) return <PublicLayout><div className="detail-loading"><Loader2 className="spin" /> Loading project</div></PublicLayout>;
  if (!project.data) return <PublicLayout><div className="detail-loading"><h1>Project not found</h1><Link className="text-button" href="/work"><ArrowLeft size={16} /> Back to our work</Link></div></PublicLayout>;
  const images = parseImages(project.data.imageUrls); if (!images.length && project.data.imageUrl) images.push(project.data.imageUrl); if (!images.length && project.data.slug === "connect4change") images.push(projectOneImage); if (!images.length && project.data.slug === "inclusive-community-development") images.push(projectTwoImage); if (!images.length && project.data.slug === "sustainable-livelihoods") images.push(projectThreeImage); const meta = parseMeta(project.data.imageMeta);
  return <PublicLayout><main><PageIntro eyebrow="" title={<>{project.data.title}</>} copy={project.data.summary} /><section className="project-detail-section"><div className="container project-detail-grid"><div className="project-detail-visual">{images.length ? <div className="project-detail-gallery">{images.map((image, index) => { const item = meta[index]; return <figure key={image}><img src={image} alt={item?.alt || `${project.data?.title} project image ${index + 1}`} /><figcaption>{item?.caption}</figcaption></figure>; })}</div> : <><FolderOpen size={38} /><span>EFEN project / {String(project.data.id).padStart(2, "0")}</span></>}</div><div><h2>Building a practical pathway from connection to change.</h2><p className="lead-copy">{project.data.detail}</p><p>EFEN's approach is grounded in listening, relationship-building and action alongside the people and communities closest to the opportunity.</p><Link className="button button-dark" href={`/involved?type=opportunity&project=${encodeURIComponent(project.data.title)}`}>Connect around this work <ArrowUpRight size={16} /></Link></div></div></section></main></PublicLayout>;
}
