import { useState } from "react";
import { ArrowLeft, ArrowRight, ArrowUpRight, FolderOpen, Loader2 } from "lucide-react";
import { Link } from "wouter";
import { PageIntro, PublicLayout, usePageMeta } from "@/components/PublicLayout";
import { trpc } from "@/lib/trpc";
import projectOneImage from "@/assets/efen-comm1.jpeg";
import projectTwoImage from "@/assets/efen-comm3.jpeg";

const parseImages = (value: string | null | undefined) => { try { const parsed = value ? JSON.parse(value) : []; return Array.isArray(parsed) ? parsed.filter((item): item is string => typeof item === "string").slice(0, 5) : []; } catch { return []; } };

export default function Work() {
  usePageMeta("Our work", "Explore EFEN projects across youth empowerment, inclusive communities, livelihoods and resilience.");
  const [page, setPage] = useState(1);
  const projects = trpc.projects.list.useQuery({ page, pageSize: 3 });
  return <PublicLayout><main><PageIntro eyebrow="" title={<>Practical pathways from <em>connection</em> to change.</>} copy="EFEN works across youth empowerment, sustainable livelihoods, inclusion, learning, climate resilience and partnership." /><section className="projects-section"><div className="container"><div className="projects-intro"><div><h2>Work that meets people where they are.</h2></div><p>Each project starts with people, then builds the connections, skills and action needed to move forward.</p></div>{projects.isLoading ? <div className="loading-state"><Loader2 className="spin" /> Loading projects</div> : <div className="projects-grid">{projects.data?.items.map((project) => { const bundledImage = project.slug === "connect4change" ? projectOneImage : project.slug === "inclusive-community-development" ? projectTwoImage : ""; const image = parseImages(project.imageUrls)[0] || project.imageUrl || bundledImage; return <article className="project-card" key={project.slug}><div className="project-card-visual">{image ? <img src={image} alt={project.title} /> : <><span>{project.category}</span><FolderOpen size={31} /></>}<b>EFEN / {String(project.id).padStart(2, "0")}</b></div><div className="project-card-body"><h3>{project.title}</h3><p>{project.summary}</p><Link className="text-button" href={`/work/${project.slug}`}>Read project <ArrowUpRight size={16} /></Link></div></article>; })}</div>}{!projects.isLoading && !projects.data?.items.length && <div className="empty-state">No published projects yet. The admin can add the first project from the private workspace.</div>}<div className="pagination"><span>Page {page} of {Math.max(1, Math.ceil((projects.data?.total ?? 0) / 3))}</span><div><button type="button" disabled={page === 1} onClick={() => setPage((value) => Math.max(1, value - 1))}><ArrowLeft size={16} /> Previous</button><button type="button" disabled={!projects.data?.hasNext} onClick={() => setPage((value) => value + 1)}>Next <ArrowRight size={16} /></button></div></div></div></section><section className="work-approach"><div className="container"><span className="eyebrow light"><i className="eyebrow-line" /> How we learn</span><h2>Reach → Connect → Empower → Act → Measure → Learn → Scale.</h2><p>We keep the work grounded in community feedback, responsible learning and partnerships that can carry useful solutions further.</p></div></section></main></PublicLayout>;
}
